# Generated by Django 4.2.4 on 2023-11-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moledordepasas', '0004_post_likes_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='cuerpo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='título',
        ),
    ]
